name: Build
on:
  workflow_dispatch:
    branches: [ main ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache libcaesium
        id: cache-libcaesium
        uses: actions/cache@v3
        env:
          cache-name: cache-libcaesium
        with:
          path: ${{github.workspace}}/build-${{ runner.os }}/libcaesium-prefix
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/libcaesium.conf') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.0.*'
          version: '6.5.3'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtimageformats'
          cache: true

      - name: Configure CMake
        run: cmake -B build_dir -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -DCMAKE_BUILD_TYPE=Release -B ${{github.workspace}}/build-${{ runner.os }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build-${{ runner.os }} --config Release --target caesium_image_compressor
      - name: Install
        run: cmake --install
      - name: Package
        run: cpack -G DEB
